name: release

on:
  release:
    types:
      - created

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version-file: .github/python-version.txt
      - run: pip3 install hatch~=1.9
      - run: hatch run dev:check

  build-docs:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version-file: .github/python-version.txt
      - run: pip3 install hatch~=1.9
      - run: hatch run docs:build-docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
